traitecoevo/austraits.build

R/steps.R
R/support.R
tests/test-setup.R

Silence output from read_csv

---

R/pre_process.R
R/report_notetaker.R
R/report_utils.R
R/setup.R
R/steps.R
R/support.R

I've provided further documentation for the functions with more detail for functions that were flagged.
There are a few functions that I have flagged that may need additional review.

Function documentation

---

scripts/README.Rmd

* updates to readme.rmd for Zenodo page

Update scripts readme.rmd

---

R/steps.R

- simplify workflow by reducing intermediate functions
- better use of purr features (name, map_df)
- implement single rename across all data
- towards #515

Optimise format_sites

---

tests/build/examples/test1-data.csv
tests/build/examples/test1-metadata.yml
tests/build/helper.R
tests/build/test-build_examples.R
tests/build/test-constancy.R

- functions to test building a study and testing structure
- placeholder for test examples

Enable more testing of build, with examples

---

data/Buckton_2019/metadata.yml

time to merge in a branch of minor fixes

Minor fixes

---

data/Dwyer_2017/metadata.yml

Replace deprecated function

---

R/setup.R

Update `metadata_add_contexts` to reflect new context format.

Update function metadata add contexts

---

config/traits.build_v000.owl

add a draft version of the traits.build ontology to GitHub repository.

Add traits.build owl

---

R/process.R

Bugfix context ids

---

config/metadata.yml
inst/support/austraits.build_schema.yml

Small updates to the database metadata tibble, to further align with DataCite and Zenodo output

Database metadata updates

---

data/Brodribb_2000/data.csv
data/Brodribb_2000/metadata.yml
remake.yml

* data transcribed from manuscript
* author not contacted, as this is an older study

Add new study: Brodribb_2000

---

data/ABRS_2023/metadata.yml
data/ATRP_2020/metadata.yml
data/NHNSW_2023/metadata.yml
data/NTH_2022/metadata.yml
data/NTH_2023/data.csv
data/NTH_2023/metadata.yml
data/RBGV_2022/metadata.yml
data/RBGV_2023/metadata.yml
data/SAH_2022/metadata.yml
data/SAH_2023/data.csv
data/SAH_2023/metadata.yml
data/WAH_2022_1/metadata.yml
data/WAH_2022_2/metadata.yml
data/WAH_2023_1/data.csv
data/WAH_2023_1/metadata.yml
data/WAH_2023_2/data.csv
data/WAH_2023_2/metadata.yml

add `plant_photosynthetic_organ`, `leaf_lamina_posture` and `leaf_margin_posture` to scraped flora data files

add 3 traits to scraped data files

---

data/Hall_1981/metadata.yml
data/Mesaglio_2022/metadata.yml
data/Pfautsch_2016/metadata.yml
data/RussellSmith_2012/metadata.yml
data/SmithMartin_2020/metadata.yml
data/Stephens_2023/metadata.yml
data/WAH_2023_2/data.csv
data/Westoby_2004/metadata.yml
data/Wilson_2004/metadata.yml
data/eFLOWER_Dun_2022/metadata.yml

* changes to metadata so the studies can pivot wider
* absolutely puzzled why some of these changes weren't made before
* these complement changes to process.R made in traits.build versions of the functions

changes to metadata, so datasets pivot wider

---

data/Purdie_1976/metadata.yml

Standardise values for time to flowering type context

Minor metadata edits to Purdie_1976

---

R/process.R
data/Witkowski_1991/data.csv
data/Witkowski_1991/metadata.yml
data/Yang_2023/metadata.yml

more fixes to pivoting problems:
- minor changes copied from traits.build back to austraits.build process.R file
- had to add locations to Yang_2023
- Witkowski_1991 would only recognised plant ages when I wrote them in letters; tried many many other tricks

more pivot errors fixed

---

data/Canham_2023/metadata.yml
data/Grigg_2008/metadata.yml
data/SinghRamesh_2019/metadata.yml

- Found in Canham_2023, Grigg_2008 and SinghRamesh_2019

Fix special characters preventing build on Windows

---

config/traits.yml
scripts/build_traits_yml_from_APD.R

* Update traits.yml from current APD
* Make minor changes to script to use APD output files, rather than inputs

Update trait dictionary

---

config/unit_conversions.csv
data/Portelli_2023/metadata.yml
data/Portelli_2023/raw/Vesk_2023_sites.csv

This study has been on a branch as "Vesk_2023" for 2 years, waiting for the manuscript to be published. Because of taxonomy list mess in September 2023, took data/metadata files for the study and moved them to a new branch. Re-ran tests, confirming everything working.
Report reviewed by Peter Vesk long ago.

Portelli_2023, add new study

---

data/Tsujii_2023/data.csv
data/Tsujii_2023/metadata.yml
data/Tsujii_2023/raw/06Feb2025Vcmax.csv
data/Tsujii_2023/raw/location_data.csv

add new study, looking at P fractions, other traits, in part on Ian Wright's Sydney-area study sites
report reviewed by contributor

add study, Tsujii_2023

---

data/Hutton_1994/data.csv
data/Hutton_1994/metadata.yml

small dataset recording collection of Ericaceae species for which ericoid mycorrhizae have been definitively identified

add Hutton_1994

---

config/traits.yml
data/SPRAT_2025_2/data.csv
data/SPRAT_2025_2/metadata.yml

add data scraped from SPRAT profiles and related sources
- add nearly 3000 trait values from SPRAT resources
- correct 1 typo from APD
- also a few trait values that will need to get added to APD, but for this release won't add them so properly synched

add SPRAT_2025_2

---

DESCRIPTION
NEWS.md
README.md
config/metadata.yml
scripts/release.Rmd

* update NEWS, DESCRIPTION, etc for release
* update config/metadata.yml

Prepare for release of v7.0.0
